### DISCUSSION TITLE
Remote Control

### DISCUSSION THREAD

**Discussion by gt008** [wills106/homeassistant-solax-modbus#1071] [General]
Hi

Firstly thank you for a great integration. I have Solax X3 25kw Ultra Gen 5 plus 2x 23.2kwh batteries and I am using Predbat to plan the cycles with Octopus Agile import, fixed export (15p). 

I can’t get my head around the remote-control functions and any help would be much much appreciated. 

1. Is it still advised to use RemoteControl rather than the default control modes (Charger Use Mode)? I think I read somewhere that Solax  Gen4/5 inverters no longer rely heavily upon EEPROMs, so RC no longer needed. I currently have PredBat working using the Charger Manual mode to force charge/discharge the batteries  and then reverting to Self Use Mode when Predbat is Idle. 
2. Am I right in saying that with Remote Power Control: Enabled Self Use that the this emulates the Charger Use Mode: Self Use, so can simply replace its use within automations ( or more specifically in PredBat)? Similarly that Charger Use Mode: Manual Mode to Force charge etc can be replaced by Remote Power Control: Enabled Power Control? 

Thank you

**Comment by romankysely** [comment]
Very usefull topic. Were do you findout info about PradBat? I have never heard about it. thx

**Reply by gt008** [reply]
PredBat is a HomeAssistant Addon that predicts the best (cheapest) battery usage (charge and discharge cycles) by modelling differing scenarios based on forecast solar production, published future grid import and export rates (Octopus Agile) and expected load (based on historical usage). It was originally written with GivEnergy inverters in mind but works with Solax with a little tweaking. However it does actively change the Charge Use mode of the inverter numerous times per day, thus my interest in using the remote control if the EEPROMs are getting cycled each time. Lots of info on GitHub and the Predbat Facebook group.

**Comment by viktorp75** [comment]
I am also wondering about this. I have X3 G4 Hybrid and tried to use RC in the past, however I did not find any affect on my system when triggering it so I must have been doing something wrong.
I currently use mostly Manual Mode - Force Charge or Force Discharge in my automations depending on situation, on a very sunny day I use Selfuse so I can also export. it works pretty well but I think I need to change things to more consider EEPROM and the battery cycles. Will check the PradBat though as I have never heard about it. Thanks

**Comment by maxgrosse1** [comment]
Hi Giles @gt008, I also started getting more insights into remotecontrol. Would you be so kind to share your latest predbat yaml.app file for the Solax inverter?
Best, Max

**Comment by ralfna** [comment]
Hi all, I also working on this with my Qcells(Solax), I did an automation with using 'Enable Grid Control' 'Enable No Discharge' and 'Disabled' to control the battery charging. Decisions are made on the EPEX price integration. Is anyone interesting in sharing thoughts about this topic?
br Ralf

**Comment by Vaszago** [comment]
I also control my Solax Ultra 15k with the Epex price. However, I only charge my batteries with a price difference of more than 8 cents. Because the loss of charge could also turn into a negative business. 2 I have activated charging only at night in my Home Assistant automation. Because during the day there is usually some PV power and I am better positioned anyway. But I don't know if that is a smart idea. Otherwise the remote control works well to protect the eeprom.

**Comment by ralfna** [comment]
yes I also added a 8 cent price delta to decide wether to charge to hold or discharge. I attached my automation, open to discuss :-)
[Ladefunktion Solaranlage.txt](https://github.com/user-attachments/files/18550038/Ladefunktion.Solaranlage.txt)
[Calculate No Discharge Price Threshold.txt](https://github.com/user-attachments/files/18550041/Calculate.No.Discharge.Price.Threshold.txt)
What I am working on is to automate the best price for charging, I am trying Google AI API in the moment, But I have not a lot of experience with AI implementation in Homeassistant...

**Reply by Xoffroad** [reply]
Remote control doesn't work on my Qcells(Solax) System to control battery discharge.
I have a simple automation, but it has no effect to my system. I can only control battery charge but no discharge. I didn't find a difference between my simply automation and your discharge script.
I use "self use mode".

```
alias: Neue Automation
description: ""
triggers:
  - trigger: state
    entity_id:
      - input_button.stoppe_ladung
conditions: []
actions:
  - data:
      value: "0"
    target:
      entity_id: number.solax_remotecontrol_active_power
    action: number.set_value
  - data:
      option: Enabled No Discharge
    target:
      entity_id: select.solax_remotecontrol_power_control
    action: select.select_option
  - data:
      value: "3600"
    target:
      entity_id: number.solax_remotecontrol_autorepeat_duration
    action: number.set_value
  - data: {}
    target:
      entity_id: button.solax_remotecontrol_trigger
    action: button.press
mode: single
```
