### DISCUSSION TITLE
Gen2 & Gen3 Export Example

### DISCUSSION THREAD

**Discussion by wills106** [wills106/homeassistant-solax-modbus#110] [Show and tell]
Example for [Gen2 & Gen3 Modes of operation](https://github.com/wills106/homeassistant-solax-modbus/wiki/Gen2-&-Gen3-Modes-of-operation)

**Gen2**
```
WIP
```

**Gen3**
```
alias: Export above X price
description: ""
trigger:
  - platform: numeric_state
    entity_id: sensor.export_rate
    above: "38"
condition:
  - condition: numeric_state
    entity_id: sensor.solax_battery_capacity
    above: "40"
action:
  - service: button.press
    data: {}
    target:
      entity_id: button.solax_grid_export
  - service: number.set_value
    data:
      value: "-3000"
    target:
      entity_id: number.solax_grid_export_limit
mode: restart
```

**Comment by wills106** [comment]
**Gen3**

Export during set time.
Will trigger an export session based on when the price updates, during the time frame set.
In my case `select.solax_export_duration` is set to 30 mins and `sensor.export_rate` updates every 30 mins.

Helpers:
```
input_datetime:
  agile_export_start_time_1:
    name: Agile Export Start Time 1
    has_date: false
    has_time: true
  agile_export_end_time_1:
    name: Agile Export End Time 1
    has_date: false
    has_time: true
  agile_export_start_time_2:
    name: Agile Export Start Time 2
    has_date: false
    has_time: true
  agile_export_end_time_2:
    name: Agile Export End Time 2
    has_date: false
    has_time: true
```
Automation:
```
alias: SolaX - Export Timed
description: ""
trigger:
  - platform: state
    entity_id:
      - sensor.export_rate
condition:
  - condition: time
    after: input_datetime.agile_export_start_time_1
    before: input_datetime.agile_export_end_time_1
action:
  - service: button.press
    data: {}
    target:
      entity_id: button.solax_grid_export
  - service: number.set_value
    data:
      value: "-5000"
    target:
      entity_id: number.solax_grid_export_limit
mode: restart
```

**Comment by wills106** [comment]
Basic Automation for SolaX Gen3 Hybrid and AC Inverters for Saving Sessions.
Still a manual process to setup.

Prerequisites:
- Setup the following helpers
  - `input_boolean.saving_session`
  - `input_datetime.saving_session_start_1`
  - `input_datetime.saving_session_end_1`
  - `input_number.saving_session_min_soc`

Create the following automation:


```
alias: Saving Sessions
description: ""
trigger:
  - platform: time
    at: input_datetime.saving_session_start_1
condition:
  - condition: state
    entity_id: input_boolean.saving_session
    state: "on"
action:
  - if:
      - condition: numeric_state
        entity_id: sensor.solax_battery_capacity
        above: input_number.saving_session_min_soc
    then:
      - service: button.press
        data: {}
        target:
          entity_id: button.solax_grid_export
      - service: number.set_value
        data:
          value: "-5000"
        target:
          entity_id: number.solax_grid_export_limit
    else:
      - service: select.select_option
        data:
          option: Default
        target:
          entity_id: select.solax_export_duration
  - condition: time
    after: input_datetime.saving_session_end_1
  - service: input_boolean.turn_off
    data: {}
    target:
      entity_id: input_boolean.saving_session
mode: single
```
Create a second automation to stop discharging when a minimum SOC value has been reached.


```
alias: Saving Sessions Min SOC
description: ""
trigger:
  - platform: numeric_state
    entity_id:
      - sensor.solax_battery_capacity
    below: input_number.saving_session_min_soc
condition:
  - condition: state
    entity_id: input_boolean.saving_session
    state: "on"
action:
  - service: select.select_option
    data:
      option: Default
    target:
      entity_id: select.solax_export_duration
  - service: input_boolean.turn_off
    data: {}
    target:
      entity_id: input_boolean.saving_session
mode: single
```
Create a Basic Dashboard with the Controls Needed
<img src="https://github.com/wills106/homeassistant-solax-modbus/assets/18155231/c3b5c7f8-2af6-489a-93db-cac49fc4ed53" height="250">

Set the Start and End Times and Export Duration based on the session length.
On the day of the session set the input_boolean to On.
Then at the set time it will start exporting and then if you have enough capacity it will end the export at the set time, or if capacity reaches your setpoint it will stop the discharge.

There are areas you could improve on, such as having another input_number to alter the export rate. I have it fixed at 5000w
You could also calculate the Export duration based off the Session duration.
