### DISCUSSION TITLE
Sofar HYDxxKTL-3P with a USB dongle

### DISCUSSION THREAD

**Discussion by hanscontr** [wills106/homeassistant-solax-modbus#1379] [Q&A]
Hi all,

First time using this integration. 
I have a Sofar Solar 3P hybrid inverter. I have it wired to Home Assistant using the USB RS485 adaptor in the picture below.
![afbeelding](https://github.com/user-attachments/assets/17636526-3859-4805-8b14-b93d22a729c0)

I now only have A and B connected, and not Ground as I couldn't get the inverter to be recognised whith ground also connected.
The inverter is recognised when using the below settings:
![afbeelding](https://github.com/user-attachments/assets/f899cda2-e6f3-49ce-8fcd-848f798baaf7)
![afbeelding](https://github.com/user-attachments/assets/84dd9626-733b-4259-994f-8c1dc8592428)

The readings however don't seem to be right and are often "unknown"
For example : 
![afbeelding](https://github.com/user-attachments/assets/dd0fb44e-3cab-4471-8e9d-cfbc03816a77)

Any tips on how best to debug? Things I could try?

**Comment by hanscontr** [comment]
Hi all,

I've done some further debugging but still can’t get stable readings from my inverter using the Solax integration.

I’ve tried disabling all non-essential sensors (such as temperature and per-phase readings) thinking it might be a timing or queueing issue (baudrate is only 9600 for the Sofar), but I'm still seeing erratic or unreliable data.

Interestingly, when I use modpoll command line tool on the same machine (Home Assistant OS) with the same USB-to-serial converter and cable, I get stable and consistent readings.

To isolate the issue, I also created a few sensors using the native Home Assistant modbus integration:
```
modbus:
  - name: usb_modbus
    type: serial
    method: rtu
    port: /dev/serial/by-id/usb-1a86_USB_Serial-if00-port0
    baudrate: 9600
    stopbits: 1
    bytesize: 8
    parity: N
    delay: 1
    sensors:
      - name: "ha_sofar_modbus_pv_power"
        unit_of_measurement: "W"
        address: 1476
        input_type: holding
        slave: 1
        scale: 100
        device_class: power
        state_class: measurement
        scan_interval: 10

      - name: "ha_sofar_modbus_battery_power"
        unit_of_measurement: "W"
        address: 1542
        input_type: holding
        slave: 1
        scale: 10
        device_class: power
        state_class: measurement
        scan_interval: 10

      - name: "ha_sofar_modbus_battery_soc"
        unit_of_measurement: "%"
        address: 1544
        input_type: holding
        slave: 1
        scale: 1
        device_class: battery
        state_class: measurement
        scan_interval: 10
```

These three sensors work flawlessly — but only when the Solax integration is disabled.

I've cross-checked the registers from [plugin_sofar.py](https://github.com/wills106/homeassistant-solax-modbus/blob/main/custom_components/solax_modbus/plugin_sofar.py) with my inverter, and they appear to match and return valid data.

It feels like I’m missing something obvious here — any suggestions?

Thanks in advance!
