### DISCUSSION TITLE
Sofar HYD 3600 ES

### DISCUSSION THREAD

**Discussion by superino1** [wills106/homeassistant-solax-modbus#204] [General]
Hi wills, I have this inverter model, before taking the necessary hardware, I wanted to know if it is compatible.. Thanks

**Comment by wills106** [comment]
Does the serial number start SE1?

**Reply by wills106** [reply]
You will have to beta test it.

It looks like it's the Single Phase version of the HYD 5K~20KTL-3PH with a lower battery voltage, so I would assume it will work with plugin_sofar.py but I will need to add in the serial number and then we will have to see which registers it returns. At the moment plugin_sofar.py is mostly setup for 3 Phase so we will have to see which entities to drop.
Otherwise we will have to try the plugin_sofar_old.py

**Reply by superino1** [reply]
Ok thank you. Now order modbus hardware.. Write you soon.

**Reply by superino1** [reply]
![IMG_20221116_193206](https://user-images.githubusercontent.com/74857272/202264975-6c3fe8c6-f40b-4b54-bac5-48ac613ea163.jpg)
It's right?
Edit A= + B= -
You have to reverse the letters, I found the manual

**Reply by wills106** [reply]
With RS485 A goes to A and B goes to B. it's not like TTL Serial where you swap the pins over.
But if it doesn't work, just swap them over anyway.
I had a quick look, but couldn't actually find a manual saying which is which.

**Comment by superino1** [comment]
![IMG_20221117_114215](https://user-images.githubusercontent.com/74857272/202425446-97436cfc-2b29-497b-9f4e-8fe74f358933.jpg)
Found this...

**Comment by superino1** [comment]
Hi wills, I put the beta version, unfortunately it still doesn't work.  The link light has now turned blue.  If I try to reverse the wires, the ACT light also turns blue.

**Reply by superino1** [reply]
log
2022-11-24 20:22:52.742 WARNING (MainThread) [custom_components.solax_modbus.plugin_sofar_old] reading serial number from address 8193 failed; other address may succeed
2022-11-24 20:22:52.747 ERROR (MainThread) [custom_components.solax_modbus.plugin_sofar_old] cannot find serial number, even not for other Inverter
2022-11-24 20:22:52.762 ERROR (MainThread) [custom_components.solax_modbus.plugin_sofar_old] unrecognized inverter type - serial number : unknown
  File "/config/custom_components/solax_modbus/number.py", line 27, in async_setup_entry
    for number_info in plugin.NUMBER_TYPES:
AttributeError: module 'custom_components.solax_modbus.plugin_sofar_old' has no attribute 'NUMBER_TYPES'
2022-11-24 20:22:53.406 ERROR (MainThread) [homeassistant.components.select] Error while setting up solax_modbus platform for select
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 281, in _async_setup_platform
    await asyncio.shield(task)
  File "/config/custom_components/solax_modbus/select.py", line 26, in async_setup_entry
    for select_info in plugin.SELECT_TYPES:
AttributeError: module 'custom_components.solax_modbus.plugin_sofar_old' has no attribute 'SELECT_TYPES'

**Reply by wills106** [reply]
Have you only tried plugin_sofar_old.py ? I was expecting it to use use plugin_sofar.py

**Comment by superino1** [comment]
Neither of them work.  But are the blue lights ok?  I say those of LINK and ACT

**Reply by wills106** [reply]
Have you followed https://github.com/wills106/homeassistant-solax-modbus/wiki/Installation-Notes
But setting baud to 9600 and Modbus Gateway Type to "Auto query storage type"

**Reply by superino1** [reply]
Nothing to do... It doesn't start.

**Comment by superino1** [comment]
I give up for today..

**Reply by wills106** [reply]
We just need to be patient, I am sure more users with the same Inverter as yours will turn up.
Then we can share our knowledge between us 😊 and understand how we can get additional Inverters working with this Integration.

**Reply by superino1** [reply]
So this inverter is not compatible for now?  Thanks for now

**Reply by wills106** [reply]
I am sure it's compatible, we just need to work on the initial communications.

**Comment by superino1** [comment]
Tell me what to do and I will do it.

**Comment by wills106** [comment]
If you add the following to your configuration.yaml do the sensors return any values?

```
modbus:
  - name: Sofar
    type: tcp
    host: 192.168.x.x
    port: 502

    sensors:
        
    - name: Sofar Serial Test1
      slave: 1
      address: 1093
      count: 7
      data_type: string
      scan_interval: 5

    - name: Sofar Grid Frequency Test1
      slave: 1
      address: 1156
      data_type: uint16
      scan_interval: 5
      
    - name: Sofar Serial Test2
      slave: 1
      address: 8193
      input_type: input
      count: 7
      data_type: string
      scan_interval: 5

    - name: Sofar Grid Frequency Test2
      slave: 1
      address: 17
      data_type: uint16
      scan_interval: 5
```
Make sure you are not trying to use the SolaX Integration at the same time.

If your Inverter is sleeping due to lack of Solar PV / Battery flat wait till the morning.
