### DISCUSSION TITLE
Run two instances to the same inverter?

### DISCUSSION THREAD

**Discussion by J14111** [wills106/homeassistant-solax-modbus#252] [Q&A]
Hi

I would like to have a dashboard that updates quickly say 5 or 10 seconds but also keep say every 60s for historic purposes, for my dashboard i use influddb and grafana

So my question is can i run two instances of this integration to the same inverter with one going to an influxdb that keeps data for 24h and one that goes to another that keeps it indefinitely?

**Comment by infradom** [comment]
I do that with one instance, just install the influxdb integration. Not only solax-modbus will be logged but everything dependent on the content of your configuration.yaml file. My example extract from configuration.yaml:

```
# influx
influxdb:
  api_version: 2
  ssl: true
  host: influx.xxx.me
  port: 8086
  token: Rblebladkdlkfqjlkdsifhjieljfxxxxxx
  bucket: home_assistant
  tags:
    source: HA
  tags_attributes:
    - friendly_name
  default_measurement: units
  exclude:
    entities:
      - zone.home
      - sensor.solax_rtc
    domains:
      - persistent_notification
      - person
  include:
    domains:
      - sensor
      - binary_sensor
      - sun
    entities:
      - weather.home
```
