### DISCUSSION TITLE
Inverter status alarms

### DISCUSSION THREAD

**Discussion by kyuzumaki** [wills106/homeassistant-solax-modbus#365] [Ideas]
Hi first off thanks for this integration it's brilliant! My idea is really just to read status messages and alarms. The only thing compared to the ginlong Solis app im missing are the inverter messages, e.g. no grid, over voltage grid ( i get this occasionally due to my location). 

Would it be possible to read this info out? I'm using a Solis 5G inverter, i believe the registers are just on off for each state alarm. This document is probably not new to anyone but at least for my inverter the registers seem to be listed for the alarms.
https://www.scss.tcd.ie/Brian.Coghlan/Elios4you/RS485_MODBUS-Hybrid-BACoghlan-201811228-1854.pdf

It would be really useful to be able see these messages with a timestamp.

**Comment by alienatedsec** [comment]
@kyuzumaki good shout, but the document is now outdated

I see this as more relevant https://213.136.68.177/assets/uploads/files/1619515984065-_without-control-hybrid-en-2020.9.15_rs485_modbus-esinv-33000id-hybrid-inverter.pdf

**Comment by wills106** [comment]
Which values are you after in particular?
33095 - Appendix 2
33116, 33121 & 33132 are reliant on https://github.com/wills106/homeassistant-solax-modbus/discussions/200#discussioncomment-4242410

33095 looks straight forward enough to implement.

**Reply by wills106** [reply]
I have just released [2023.03.2b11](https://github.com/wills106/homeassistant-solax-modbus/releases/tag/2023.03.2b11) and included a few "Inverter Status" results for 33095
@kyuzumaki can you let me know if they display correctly for Grid Loss and Grid Overvoltage.

**Reply by alienatedsec** [reply]
@wills106 missing description in your b11 release for https://github.com/wills106/homeassistant-solax-modbus/releases/tag/2023.03.2b7 and b7 seems to have the wrong headings too. Sorry just spotted that

**Reply by wills106** [reply]
I know b7 was wrong (Just corrected the title). But b11 shows up ok to me?

![image](https://user-images.githubusercontent.com/18155231/228873274-679bc5e6-d123-40ca-a3c2-8edc4a26b481.png)
![image](https://user-images.githubusercontent.com/18155231/228873410-71248877-9ba7-4f1e-bb11-c6017423cf57.png)

Edit: I see what you mean now, it's missing the description of the change in b7
Edit 2: Just added the changes into b11 readme

**Reply by kyuzumaki** [reply]
Ok B11 didnt show the sensor but B14 has it and it is working as expected. I cut the grid to my inverter and it detected it instantly. I'm not sure about grid over voltage and battery overvoltage I will have to monitor for those as I cant simulate them

**Comment by kyuzumaki** [comment]
Thanks for adding that. I thought it would be useful to have all the potential error codes in there in case of a fault. I've copied them all out from the document into my local version and it seems to work fine.

Have added a pull request for the extra status codes.

**Reply by alienatedsec** [reply]
@kyuzumaki which document you used?

**Reply by kyuzumaki** [reply]
The one you posted in this thread

**Reply by alienatedsec** [reply]
@kyuzumaki thanks. I have not checked your PR yet but that would be also my reference document for input registers.

**Comment by kyuzumaki** [comment]
Working well now. I've combined this with a notification Automation and its essentially replicated the Solis app functionality. This adds an entry to the home assistant notifications section and sends one to a mobile device. 

It's set up for iOS devices so might need slight alteration for android.

The only thing I noticed is the inverter status entity dosent show a logbook. Not sure why that is. The HA docs dont go into much detail on that popup.

```
alias: Inverter Notifications
description: Sends inverter status when it changes
trigger:
  - platform: state
    entity_id:
      - sensor.solis_5g_inverter_status
condition: []
action:
  - device_id: <<INSERT YOUR DEVICE>>
    domain: mobile_app
    type: notify
    message: "{{states('sensor.solis_5g_inverter_status')}}"
    title: Inverter status change
    data:
      push:
        sound:
          name: default
          # Critical optional flag to make it a critical alert, remove line for normal notification
          critical: 1
          volume: 1
        badge: 1
  - service: notify.persistent_notification
    data:
      message: "{{states('sensor.solis_5g_inverter_status')}}"
      title: Inverter Status Change
mode: single
```
