### DISCUSSION TITLE
dynamic charging with agile octopus

### DISCUSSION THREAD

**Discussion by motclem** [wills106/homeassistant-solax-modbus#38] [Q&A]
I've got the agile octopus integration successfully puling in process the next obvious step is to automate when my solax battery charges Ie when the price drops below a defined threshold 
I' guessing I need a helper to define my threshold but other than that not sure where the best place to start is my gut reaction is a standard automation wouldn't be able to do it because of the half hour slots element of both the price and solax charging parameters Amy ideas greatly appreciated this has been the holy grail of my HA adventure :) the superb work  of @wills106  makes it feel like its within reach

**Comment by wills106** [comment]
I guess the simplest method would be to have your Force times set to charge the battery 24hrs and then cycle between Self Use and Force Time based on the price dropping below X.

```
alias: Agile Battery Charge
description: ''
mode: restart
trigger:
  - platform: numeric_state
    entity_id: sensor.octopus_agile_current_rate
    below: '10'
condition: []
action:
  - service: select.select_option
    data:
      option: Force Time Use
    target:
      entity_id: select.solax_charger_use_mode
  - delay:
      hours: 0
      minutes: 30
      seconds: 0
      milliseconds: 0
  - service: select.select_option
    data:
      option: Self Use Mode
    target:
      entity_id: select.solax_charger_use_mode
```

Ideally you would want to dynamicly change the times based on the aglie time slots.
