### DISCUSSION TITLE
SofarSolar and EVCC: Disable home battery, when switching to 'now' charging mode.

### DISCUSSION THREAD

**Discussion by cschlipf** [wills106/homeassistant-solax-modbus#612] [Show and tell]
This automation automates a SofarSolar HYD xx KTL in combination with EVCC to disabled the home battery while charging in 'now' mode.

It consists of three automations:

First automation disables the home battery by switching to passive mode and setting the charging/discharging power to 0:

```yaml
alias: "Charge now: Deactivate home battery"
description: ""
trigger:
  - platform: state
    entity_id:
      - select.evcc_mode
    to: now
condition: []
action:
  - service: select.select_option
    data:
      option: Passive Mode
    target:
      entity_id: select.sofar_charger_use_mode
  - service: number.set_value
    data:
      value: "0"
    target:
      entity_id: number.sofar_passive_mode_battery_power
  - service: button.press
    data: {}
    target:
      entity_id: button.sofar_passive_mode_battery_charge_discharge
mode: single
```

The next one activates the home battery again, when someone changes the charging mode from now to anything else by setting the use mode back to "self use":

```yaml
alias: "Charge now: End of mode: Activate home battery"
description: ""
trigger:
  - platform: state
    entity_id:
      - select.evcc_mode
    from: now
condition: []
action:
  - service: select.select_option
    data:
      option: Self Use
    target:
      entity_id: select.sofar_charger_use_mode
mode: single
```

And lastly the last automation activate he home battery again and resets the EVCC charging mode back to 'pv' after charging has been stopped (e.g. charge limit reached or car disconnected):

```yaml
alias: "Charge now: Charging stopped: Activate home battery and reset charging mode"
description: ""
trigger:
  - platform: state
    entity_id:
      - binary_sensor.evcc_loadpoint_charging_garage
    to: "off"
    from: "on"
condition:
  - condition: state
    entity_id: select.evcc_mode
    state: now
action:
  - service: select.select_option
    data:
      option: pv
    target:
      entity_id: select.evcc_mode
  - service: select.select_option
    data:
      option: Self Use
    target:
      entity_id: select.sofar_charger_use_mode
mode: single
```
