### DISCUSSION TITLE
ESO’s Demand Flexibility Service paying £2.25-£3/kw export

### DISCUSSION THREAD

**Discussion by visitdigital** [wills106/homeassistant-solax-modbus#643] [Q&A] [answered]
# Tapping into ESO's Demand Flexibility Service for Solax Battery Management

Solaxers!

I'm exploring an opportunity to align my home energy setup with the ESO's Demand Flexibility Service (DFS). The goal is to leverage Home Assistant for management of my Solax battery in response to DFS events.

<img width="1131" alt="Screenshot 2023-11-27 at 10 45 23" src="https://github.com/wills106/homeassistant-solax-modbus/assets/1809171/280075c5-30a9-4c7e-97b0-c13c8a3663ad">

## Current Setup
- Solax battery, set to charge off-peak (12:30-4:30 AM) on Octopus Go.
- X1-AC 3.6kw with 2 x 5.8kw V2's
- Home Assistant with Waveshare modbus.
- Apple Watch for control (using HA Companion mode).

## Objective
1. **Pre-Event Charging**: Configure the Solax battery to charge a few hours before a DFS event. This action should be triggerable via HA, potentially using an Apple Watch command. Here are some triggers i have on my watch already including some to set the max charge to 25,50,75 and 100% depending on the solar forecast the next day.

![incoming-AC7D3F4A-DDFC-4D1F-8C53-7E95C484EB91](https://github.com/wills106/homeassistant-solax-modbus/assets/1809171/e8069ed8-3df8-4764-afbc-ced56c68792c)

![incoming-AB43A504-F68A-4AE1-BD9F-72280D41B729](https://github.com/wills106/homeassistant-solax-modbus/assets/1809171/6e58d8b9-7404-4699-b99c-0e247b2be7dc)

3. **Event Discharge**: During a DFS event, trigger the Solax battery to discharge, either at a preset time aligned with the DFS schedule or through a HA trigger via the Apple Watch.

## Challenges & Questions
1. **Apple Watch Integration**: Tips for setting up HA triggers through the Apple Watch for immediate control and response.
2. **Maximise Export**: Strategies for optimising this setup to take full advantage of the higher rates offered during DFS events. I think these are going to become more common.
3. **Revert Back**:How do we Immediately revert back to pre configured off peak charging.

Question, how do i get Solax to discharge on demand via Modbus?

Thank you for your time and expertise!

Lee

**Comment by visitdigital** [comment]
Here is my pre charge trigger:
 
```
alias: Charge Battery Pre ESO Event
description: "This sets the battery to charge 1.5hours ahead of a ESO event starting at 5pm at peak rate"
trigger:
  - platform: event
    event_type: ios.action_fired
    event_data:
      actionName: Charge Battery ESO
condition: []
action:
  - device_id: 392aefd9242994ceffbae515d5545d90
    domain: select
    entity_id: 5a16293c4e2b04b7214b6e5dd6b4655f
    type: select_option
    option: "15:30"
  - device_id: 392aefd9242994ceffbae515d5545d90
    domain: select
    entity_id: 22d80f911655ff1c31ffb074178ccc4d
    type: select_option
    option: "15:30"
  - device_id: 392aefd9242994ceffbae515d5545d90
    domain: select
    entity_id: 8ee7fbba4ef25c49440a40b42b7bd71a
    type: select_option
    option: "17:00"
  - device_id: 392aefd9242994ceffbae515d5545d90
    domain: select
    entity_id: f4cff70a808dfee1f1c8ab5ced5fa71b
    type: select_option
    option: "17:00"
mode: single

```

Here is my post charge trigger to reset to off peak charging:

```
alias: "Charge Battery Reset POST ESO Event "
description: "Post ESO event, this trigger sets the battery to charge at the regular Octopus Go hours."
trigger:
  - platform: event
    event_type: ios.action_fired
    event_data:
      actionName: Reset Battery to off peak
condition: []
action:
  - device_id: 392aefd9242994ceffbae515d5545d90
    domain: select
    entity_id: 5a16293c4e2b04b7214b6e5dd6b4655f
    type: select_option
    option: "00:45"
  - device_id: 392aefd9242994ceffbae515d5545d90
    domain: select
    entity_id: 22d80f911655ff1c31ffb074178ccc4d
    type: select_option
    option: "00:45"
  - device_id: 392aefd9242994ceffbae515d5545d90
    domain: select
    entity_id: 8ee7fbba4ef25c49440a40b42b7bd71a
    type: select_option
    option: "04:30"
  - device_id: 392aefd9242994ceffbae515d5545d90
    domain: select
    entity_id: f4cff70a808dfee1f1c8ab5ced5fa71b
    type: select_option
    option: "04:30"
mode: single

```
