### DISCUSSION TITLE
Help with Modbus Power Control (remotecontrol power)

### DISCUSSION THREAD

**Discussion by gjpgjp** [wills106/homeassistant-solax-modbus#682] [Q&A]
I’ve used the really helpful wiki to enable automation to charge my battery when the intelligent octopus import rate is low. 

`input_number:
  no_discharge_price_threshold:
    name: No discharge price threshold
    unit_of_measurement: €
    min: 0
    max: 0.50
    step: 0.001
  charge_price_threshold :
    name: Charge price threshold
    unit_of_measurement: €
    min: 0
    max: 0.5
    step: 0.001
  charge_duration :
    name: Charge duration
    unit_of_measurement: s
    min: 0
    max: 18000
    step: 3600
  target_soc :
    name: Target SOC
    unit_of_measurement: '%'
    min: 50
    max: 98
    step: 2`

However when the battery reaches 100%  it immediately starts to discharge even though the rate it still low. 

Is there a way I can change this automation to continue to keep the battery charging until the rate goes back up? (or keep the battery at 100% and the house load taken from grid until the rate goes back up). 

In my test last night the battery started discharging about 4am even though the low rate on Octopus stays until 5.30 am. 

![IMG_2939](https://github.com/wills106/homeassistant-solax-modbus/assets/46397673/51a6faca-d5d0-4fdc-b310-cfaf296cc25a)

**Comment by infradom** [comment]
You may need a couple af automations (one to start the charge and one to stop the charge when battery is almost full or when price exceeds a threshold). The code in the wiki are just examples to help you get started.
Also watch the configured duration of the charge, the default duration may cause what you observed.
In my recent versions, I added a second trigger that runs every hour, to reevaluate the situation and make sure that the duration has not expired:

I just updated the examples in the wiki with this second time based trigger. 
I also added a stop automation for this charge mode.

**Reply by gjpgjp** [reply]
Thank you so much for your help!

I've tried the new automation but don't have an entity called `input_boolean.charge_from_grid`

Is this something I need to set up seperately?

**Reply by infradom** [reply]
Sorry, yes you may need to create this input_boolean in your config/configuration.yaml; or remove that part of the automation code.

Example from my config/configuration.yaml :
```
input_boolean:
  morning_discharge:
    name: Morning Discharge Enable
  evening_discharge:
    name: Evening Discharge Enable
  charge_from_grid:
    name: Charge From Grid Enable
  feedin_enabled:
    name: Feedin Prio Enabled
  house_from_grid_enabled:
    name: Houseload from Grid Enable
  no_discharge_enabled:
    name: No Discharge Enable
```
I updated the wiki page to include part of this
