### DISCUSSION TITLE
Newbie to Solax and this integration, some issues/questions.

### DISCUSSION THREAD

**Discussion by blb4github** [wills106/homeassistant-solax-modbus#74] [General]
First of all: thanks for this integration!! Last week I've bought a second hand SK-SU3000E system with 6,5 kWh LG battery and still discovering the system. I like to control the system myself and it looks like this integration is going to help me a lot!!

First of all I have to say it's a steep learning curve to start with the integration, especially as I'm not that much into HA. I had to google HACS to understand what that means and YouTube to figure out how to install that.... That's not something you can change a lot...

After installing this integration it was also not that easy to start:
1) it's not that clear which Generation has modbus via Ethernet and that modbus doesn't work via wifi is also not that obvious.
2) Setting up the integration it seems it's enough to provide the IP address of the system, nothing more but that is also not that clear in some documentation or the readme.
So I hope I have done the setup correctly with an Ethernet connection to the system and just provided the IP address of the system in the integration. Or is there anything else I have to configure?

3) It looks like the integration is working, I see 1 app with 55 entities but it seems I can only read (most, but not all) system data and not control the system. I have tried all 3 buttons I have seen in the integration but I don't see any action from them.
Is there anything I have to do to be able to control the system?

**Comment by wills106** [comment]
I am surprised the Integration works at all with your Inverter as I don't have any 3kW SK-SU serial numbers in the Integration.
Does your Inverter serial also start U50E then?

If it's different can you share the first 4 digits?

**Reply by blb4github** [reply]
Hi wills106, the first 4 digits of the serial number are U30E. I guess the interface is the same as the 5 kW version, in the manual they don't make any differences in the user menu, the difference is only is the power specifications.
<img width="630" alt="Schermafbeelding 2022-05-23 om 21 03 02" src="https://user-images.githubusercontent.com/35904565/169888639-e2ca9424-ef2c-4be4-a7f4-92f3c070c0b9.png">

I guess, the first 4 digits of the SK-SU3700E will be U37E then.

**Comment by larsboelen** [comment]
Hi I have a second hand SK-SU3000e (serial U30EF) as well and  the integration work that has been done is great. I am still very new to the subjects Solax and HomeAssistant but a quick learner. I started with a fresh HomeAssistant and this integration and the Solax is found with 85 entities (a lot automatically disabled). Because I have flexible tarif I would like to use the Force Time option. Even just setting it to Force Time Use on the inverter I cannot activate charging from the grid. The LG battery is at 16% so maybe it needs to have a minimum level to start charging with 2,5 kW? Any experience on how to get this working **blb4github**? I read the Wiki but couldnt find anything that helps me understand the inverter better

**Reply by wills106** [reply]
If you can't get the timed charges to work you might need to press button.solax_unlock_inverter first, if you haven't connected the Inverter to the cloud.

**Reply by blb4github** [reply]
Hi Lars,

I'm not using this Forced time Option very actively, my default use mode is Self Use Mode. But I can use it and it works for me as expected. I have not seen any charge level restriction, I did use it once the battery was only 8% and it started charging with 2500W

**Reply by larsboelen** [reply]
That did the trick, thanks! It works great now. Also the Solax was still in summer time :-)

**Comment by larsboelen** [comment]
I can now manually control the Solax with this integration and am starting to look into automation. The functionality that I am trying to automate is : change "Solax charger start time 1" to a time when flex tariffs are low and then, just before that moment arrives switch "Solax Charger use Mode" to "Forced Time use" and go back to Self Use when Solax Battery Capacity > 95%. Is there a way to do this in NodeRed without using the complex "Modbus write registers" functions?

**Reply by wills106** [reply]
Can't NodeRed change the states of the select entities?
I'm doing this with my Solar Diverter:

```
alias: Delay Solar Diverter
description: ""
trigger:
  - platform: state
    entity_id: sensor.myenergi_eddi_status
    to: Max temp reached
condition: []
action:
  - service: automation.turn_off
    data: {}
    target:
      entity_id: automation.turn_off_solar_diverter_below_100w_pv
  - service: automation.turn_off
    data: {}
    target:
      entity_id: automation.turn_on_solar_diverter_above_100w_pv
  - device_id: 1c43
    domain: select
    entity_id: select.myenergi_eddi_operating_mode
    type: select_option
    option: Stopped
  - delay:
      hours: 1
      minutes: 0
      seconds: 0
      milliseconds: 0
  - device_id: 1c43
    domain: select
    entity_id: select.myenergi_eddi_operating_mode
    type: select_option
    option: Normal
  - service: automation.turn_on
    data: {}
    target:
      entity_id: automation.turn_off_solar_diverter_below_100w_pv
  - service: automation.turn_on
    data: {}
    target:
      entity_id: automation.turn_on_solar_diverter_above_100w_pv
mode: single
```
