### DISCUSSION TITLE
SolaX X3 Hybrid G4 - Modbus Control Issue - No PV production

### DISCUSSION THREAD

**Discussion by fxstein** [wills106/homeassistant-solax-modbus#833] [General]
Hi,

On two separate installs with SolaX X3 Hybrid G4 15kW inverters I am having the issue that any modbus control option will always turn off PV production as long as the modbus control is active (not disabled).

[Solax Modbus Documentation](https://homeassistant-solax-modbus.readthedocs.io/en/latest/modbus-power-control/)

Per documentation PV power should should go to battery, houseload and then the grid (when in self use mode), but the moment I turn on Power Control, Battery Control or Enabled No Discharge, the PV production goes to ZERO.

Any ideas what could be causing this?

Best,

Oliver

**Comment by Bart39** [comment]
I think I am having the same issue with an X1 Hybrid G4,
Has been working flawlessly until a recent release - not sure which one as I only noticed it happening today

**Comment by jimbaxter** [comment]
I have had a similar issue and started to wonder if I am misunderstanding the API.
I believe it is caused by the battery reaching 100%. At this point the PV power will drop from around 5kW to a 38 watts.

I have some screenshots of my variables at the time.

![No_PV_20240602-150902](https://github.com/wills106/homeassistant-solax-modbus/assets/2590747/ed3d9efc-0422-4e68-9c1f-b8808df30a0e)
![NoPV_20240602-150906](https://github.com/wills106/homeassistant-solax-modbus/assets/2590747/08790c10-4d85-4cbe-beca-0433e5368589)

I am triggering the action via an automation:

```
action:
  - service: number.set_value
    data:
      value: "0"
    target:
      entity_id: number.solax_remotecontrol_active_power
  - service: select.select_option
    data:
      option: Enabled No Discharge
    target:
      entity_id: select.solax_remotecontrol_power_control
  - service: number.set_value
    data:
      value: "1800"
    target:
      entity_id: number.solax_remotecontrol_autorepeat_duration
  - service: button.press
    data: {}
    target:
      entity_id: button.solax_remotecontrol_trigger
  - service: notify.mobile_app_pixel_8_pro
    metadata: {}
    data:
      message: Houseload From Grid Activated
      title: Homeassistent state change
```
