### ISSUE TITLE
[Bug]: setting charge/discharge times/current is temperamental 

### ISSUE THREAD

**Issue by SzosszeNET** [wills106/homeassistant-solax-modbus#1029]
### Describe the bug

I'm using predbat to automate charge/discharge and since the last couple updates seeing inconsistencies when predbat is setting schedules resulting in discharging the battery or not charging when expected as the time windows overlap.
Sometimes when manually settings schedules through the solax integration (and predbat disabled) the schedule changes are discarded (despite pressing the set button within seconds ) but no errors nothing that would point into the direction of some possible issues.

### Integration Version

2024.8.13

### Homeassistant core version

2024.8.3

### Inverter brand

Solis 

### Plugin used

plugin_solis.py

### Serial prefix

603102

### Connection Method

modbus

**Comment by bryanajwells** [comment]
I'm seeing the exact same thing.  Sometimes the times are passed through 100% no issues, othertimes bits are missed.
For me my setup is as per https://github.com/alienatedsec/solis-ha-modbus-cloud

Method of reproducing:
I add    timed_charge_start_hours, timed_charge_start_minuts, timed_charge_end_hours and timed_charge_end_minutes to a dash board along with the button Inverter Update Charge/Discharge Times

I set the start/end time to   01:02  03:04
press the update button

Then dialing into the soliscloud interver control page I check the charge date/times match what was set.

Then set the times to something else (usually 00:00 / 00:00), check the soliscould again

Repeat, eventually one or more of the 4x digits doesn't set.

I think there may be a corrolation to the 0/5/10/15 etc. minute intervals of the hour, but there is no real pattern.

Note: not related to predbat, just really exposed by it.

**Comment by timstephenson20** [comment]
Our setup here is different in that I have HA talking Modbus direct to the datalogger and ditched SolisCloud but when getting automations running I did notice that unless I included a delay of at least 2 seconds between setting timed charge hour/minute/current values and triggering the update button, it didn't always work.  Sounds like a similar problem to what you're seeing in that times wouldn't always be set properly. 

Don't know if you immediately trigger the update after setting values but might be worth trying adding a delay to see if that helps. 

<img width="1065" alt="image" src="https://github.com/user-attachments/assets/e0c54bf6-9815-4cae-b79b-44de302e59e3">

**Comment by bryanajwells** [comment]
@timstephenson20 - My controls are on a dashboard 
![image](https://github.com/user-attachments/assets/43f4824a-0765-492d-aebb-7d9100274366)
so there would be a natural delay between setting all 4 numbers and pressing the update button.  However how much time between the last number and the update would be quite small I guess.  I'll experiment with adding a delay.

**Comment by timstephenson20** [comment]
Ah, was working on the basis you were running this in a script/automation somewhere.  It was quite fussy if memory serves - think I'd assumed at the time the issue was down to the natural latency between submitting values in HA, HA sending them to the Datalogger and the Datalogger then writing them to the inverter - give it a couple of seconds for everything to happen and the problem went away.

**Comment by SzosszeNET** [comment]
Yes but bottom line it became an issue with the latest releases, went back all the way I could 2024.04.3 (potentially could go higher) and not experiencing the issue.

**Comment by j47996** [comment]
Also seeing this; used to work before a recent version update

**Comment by bryanajwells** [comment]
@wills106 
This is still happening on 2024.09.5
Attached is an image of predbat setting the start hours to 23:30, but the inverter not getting this value and triggering a charge.  The 3rd picture shows the hours as recorded by this integration which initially shows 23, then a few mins later changes to 0.
The minutes was uploaded successfully.
Note: I manually cancelled the charge.

To me it seems like the values are accepted by the integration, but some how this occasionally fails to be pushed to the inverter.

I have enabled debugging and hope to catch a future event. It appears from my recent leccy bill that this occurs fairly fequently
![PredBat](https://github.com/user-attachments/assets/a406aa26-7278-49d5-88bd-bac874ada65a)
![Import](https://github.com/user-attachments/assets/6afabe68-8904-4bbc-97e9-bcf415425864)
![Setting of Hours](https://github.com/user-attachments/assets/bb7c3df9-59bc-4f60-b05f-39cdca17a2f6)

**Comment by bryanajwells** [comment]
> Also seeing this; used to work before a recent version update

Do you know which version it was deffo working in?

**Comment by simondrake** [comment]
I've not seen this issue since I moved over to using helpers and a script. I had to create eight helpers in the format of `input_number.solar_{charge,discharge}_{end,start}_{hours,minutes}`; for example `input_number.solar_charge_start_hours`. 

I then created a `Set Charge/Discharge` script that uses those helpers, to set the integration entities and then "presses" the `update charge/discharge times` button:

```yaml
alias: Set Charge/Discharge
sequence:
  - action: number.set_value
    metadata: {}
    data:
      value: "{{ (states('input_number.solar_charge_start_hours') | int)}}"
    target:
      entity_id: number.solis_timed_charge_start_hours
  - action: number.set_value
    metadata: {}
    data:
      value: "{{ (states('input_number.solar_charge_start_minutes') | int)}}"
    target:
      entity_id: number.solis_timed_charge_start_minutes
  - action: number.set_value
    metadata: {}
    data:
      value: "{{ (states('input_number.solar_charge_end_hours') | int)}}"
    target:
      entity_id: number.solis_timed_charge_end_hours
  - action: number.set_value
    metadata: {}
    data:
      value: "{{ (states('input_number.solar_charge_end_minutes') | int)}}"
    target:
      entity_id: number.solis_timed_charge_end_minutes
  - action: number.set_value
    metadata: {}
    data:
      value: "{{ (states('input_number.solar_discharge_start_hours') | int)}}"
    target:
      entity_id: number.solis_timed_discharge_start_hours
  - action: number.set_value
    metadata: {}
    data:
      value: "{{ (states('input_number.solar_discharge_start_minutes') | int)}}"
    target:
      entity_id: number.solis_timed_discharge_start_minutes
  - action: number.set_value
    metadata: {}
    data:
      value: "{{ (states('input_number.solar_discharge_end_hours') | int)}}"
    target:
      entity_id: number.solis_timed_discharge_end_hours
  - action: number.set_value
    metadata: {}
    data:
      value: "{{ (states('input_number.solar_discharge_end_minutes') | int)}}"
    target:
      entity_id: number.solis_timed_discharge_end_minutes
  - action: button.press
    metadata: {}
    data: {}
    target:
      entity_id: button.solis_update_charge_discharge_times
description: ""
```

I've then changed my dashboard to use this mechanism and have included the integration entities so I can keep a close eye and ensure they don't reset to the zero value.

![image](https://github.com/user-attachments/assets/54f4e7a0-8b2f-4d37-b0bc-480cbd363092)

This obviously only enables the first charging/discharging to be used, but if/when I need the second/third variants I'll create more helpers and another script to handle it.

Like I said, I've been using this for a couple days now and haven't seen a single issue of resetting. Whether that's indicative of the **actual** issue, perhaps it needs to be set in a specific amount of time or it fails, I don't know at this time.
