### ISSUE TITLE
[Bug]: 'Azzurro/Sofar HYD ZSS' Strange time shift in the recordings

### ISSUE THREAD

**Issue by Hetzi74** [wills106/homeassistant-solax-modbus#1344]
### Describe the bug

I have a strange issue at a Azzurro/Sofar inverter!

The values are correct in themselves. But the recording is as if there is an ever-increasing time difference.

[Image](https://github.com/user-attachments/assets/27c2622e-126d-429d-8310-2b7d4c4ba698)

The picture shows production on a sunny day. I restarted the Home Assistant with the red arrows. After the restart, the values are correct so far, but the recording and reality drift apart in time. After restarting again in the afternoon, the same applies. Sunset for me is currently at 20:00, but production still appears in the recording after 21:00!

What could be the reason for this behavior?

### Integration Version

2025.04.2

### Homeassistant core version

2025.4.4

### Inverter brand

Azzurro/Sofar

### Plugin used

plugin_sofar.py

### Serial prefix

ZP1ES020N...

### Connection Method

LSE-3 LAN Stick

**Comment by cschlipf** [comment]
What does the inverter system time say? Is this in sync with your real time?

Note that the LSE-3 stick does to sync your inverters system time with a time server.

I use an automation that does that regularly instead:

```yaml
alias: Update Sofar System Time
description: ""
triggers:
  - trigger: time
    at: "00:00:00"
conditions: []
actions:
  - action: button.press
    metadata: {}
    data: {}
    target:
      entity_id: button.sofar_sync_rtc
mode: single

```
