### ISSUE TITLE
[Bug]: RemoteControl does not work well

### ISSUE THREAD

**Issue by rob11-redfordxx** [wills106/homeassistant-solax-modbus#1429]
### Describe the bug

Trying the new RemoteControl modes...
Mode 1. Does not run. After like 10 seconds comes back to normal
Mode 2. Looks ok
Mode 3, 8, 9 does not stop when reaching time/target

Not sure if it is HA integration problem or SolaX inverter itself.

the using is quite fragile, but shows potential 

### Integration Version

2025.05.3

### Homeassistant core version

2025.5.3

### Inverter brand

Solax

### Plugin used

plugin_solax.py

### Serial prefix

H34A10

### Inverter firmware versions

ARM 1.47-1.09 DSP 1.,50

### Connection Method

WiFi 3.0 Dongle

### Dongle firmware

3.019.01

**Comment by ggg1psyyy** [comment]
I've only really tested mode 9 to use negative import prices, and it seems to work like it should.
Don't forget to set all non used values to "0" at least for modes 1-7 (not sure if needed for modes 8 & 9) as proposed by https://kb.solaxpower.com/solution/detail/2c9fa4148ecd09eb018edf67a87b01d2 
That's why I added all registers as "direct", I'm sure we could do this in the addon, but I didn't want to change the current behavior.
Also be aware that the same register "0xA6" get's written with two entities "solax_remotecontrol_duration_8_direct" and "solax_remotecontrol_target_soc_9_direct", so be sure to only use the one corresponding to the chosen mode (8 or 9).
And don't use the trigger!
If you have any ideas how to do it better/easier, I'm wide open for ideas ;)

**Comment by rob11-redfordxx** [comment]
Maybe let's break it down step by step:
Mode 1: It enters the Normal(R) mode and exits after 20 sec or so.
Is there any way to send some debug log or so?
I am running VBox on Windows

**Comment by ggg1psyyy** [comment]
For mode 1-3 I would propose to use the built-in RemoteControl with trigger, as you have to repeat the command regularly. Modes 4-7 should work as described in https://kb.solaxpower.com/solution/detail/2c9fa4148ecd09eb018edf67a87b01d2 and modes 8 & 9 should work perfectly fine if you set "0xA0" - "0xA7" respectively. Don't forget to set the other registers to "0", and only changing the mode without setting the necessary other registers doesn't do anything (or worse).
All the necessary registers are described in the Solax KB entry and I tried to name them according to this document and the Solax Modbus manual.
There is no way to really debug this, as the inverter is doing everything itself and the only hint is the runmode and watching the corresponding real time values.

**Comment by rob11-redfordxx** [comment]
I suppose RC with trigger does not work (repeat), when the connection between HA and Solax is lost while Direct works, right?

About setting all other registers to zero: When I see in HA zero (or any value) it means the registers are set? Or it is not necessary true? E.g. when I restart HA, I see zero everywhere. It means there are zeroes? Or I need to set every value to nonzero and then zero back (or desired value), and then choose the Select?

**Comment by ggg1psyyy** [comment]
Yes, the trigger needs the connection, and no, only some of the registers for the remote commands can be read, others are write only, so after HA restart or connection reset the values may be differing.

**Comment by rob11-redfordxx** [comment]
I really do not know, what I am doing wrong...
BTW, when I am setting mode 8 and 9, which dropdown should I use? Modbus direct or RemoteControl direct? (and the other leave disabled)
Can I leave timeout 0, when I want to return to normal mode immediately after reaching the goal?
When I want to do duration mode, I should set Target SoC 0% ?

**Comment by infradom** [comment]
> I've only really tested mode 9 to use negative import prices, and it seems to work like it should. Don't forget to set all non used values to "0" at least for modes 1-7 (not sure if needed for modes 8 & 9) as proposed by https://kb.solaxpower.com/solution/detail/2c9fa4148ecd09eb018edf67a87b01d2 That's why I added all registers as "direct", I'm sure we could do this in the addon, but I didn't want to change the current behavior. Also be aware that the same register "0xA6" get's written with two entities "solax_remotecontrol_duration_8_direct" and "solax_remotecontrol_target_soc_9_direct", so be sure to only use the one corresponding to the chosen mode (8 or 9). And don't use the trigger! If you have any ideas how to do it better/easier, I'm wide open for ideas ;)

I was the original author of the remote_control_recompute loop mechanism, that recomputes the power needs every x seconds. I have been inactive last year, and am glad to see Solax has added new parameters like PVPowerLimit. I especially want to use this in negative price scenarios. In my case, there are 2 different negative price scenarios:

- injection prices are negative
- injection and consumption prices are negative

The latter case is simple, since we can  just limit the PV Power to zero. In the first case (only injection prices are negative), we may need a new recompute loop that computes the needed PV power from the house load and desired battery charge speed. I intend to implement this in the coming days/weeks but would like to hear other opinions first.

**Comment by rob11-redfordxx** [comment]
Maybe to make clear, what needs to be set zero (except what is needed):
Dropdown 8,9
Set 8,9
5 sensors for 8,9
Dropdown 1-9
Set 1-9
8 sensors 1-7
Total 17 items for direct?
Am I missing something?

Several times I succeded with settings mode 8, PV limit 5000, 8 push power 6000, no export, to situation like battery not charging, house powered from sun (exactly what is needed, not 5000) and battery only when needed...., which is perfect during negative sell and waiting for negative buy later in the day...but it lasted like 11 minutes.
Then again when it worked like: when PV limit is higher than house, the excess production went to battery, even when batter was set to discharge.

**Comment by ggg1psyyy** [comment]
you can take a look at my automation for switching modes according to buy and sell price: https://github.com/ggg1psyyy/NetDeamonApps/blob/master/HA/Mode.yaml
I'm using my own NetDeamon app to react to prices and loads, but in the end it just calls these automations:
if sell price is negative: "HOUSE_ONLY"
```
 - conditions:
          - condition: trigger
            id:
              - HOUSE_ONLY
        sequence:
          - action: select.select_option
            metadata: {}
            data:
              option: Self Use Mode
            target:
              entity_id: select.solax_charger_use_mode
          - action: number.set_value
            metadata: {}
            data:
              value: "10"
            target:
              entity_id: number.solax_export_control_user_limit
```
if buy price is negative: "FORCE_CHARGE_GRID_ONLY"
```
- conditions:
          - condition: trigger
            id:
              - FORCE_CHARGE_GRID_ONLY
        sequence:
          - action: number.set_value
            metadata: {}
            data:
              value: "0"
            target:
              entity_id:
                - number.solax_remotecontrol_timeout_direct
                - number.solax_remotecontrol_active_power_direct
                - number.solax_remotecontrol_charge_discharge_power_direct
                - number.solax_remotecontrol_duration_direct
                - number.solax_remotecontrol_push_mode_power_direct
                - number.solax_remotecontrol_reactive_power_direct
                - number.solax_remotecontrol_target_energy_direct
                - number.solax_remotecontrol_target_soc_direct
                - number.solax_remotecontrol_timeout_8_9_direct
          - delay:
              hours: 0
              minutes: 0
              seconds: 2
              milliseconds: 0
          - action: number.set_value
            metadata: {}
            data:
              value: "100"
            target:
              entity_id: number.solax_remotecontrol_target_soc_9_direct
          - action: number.set_value
            metadata: {}
            data:
              value: "0"
            target:
              entity_id:
                - number.solax_remotecontrol_pv_power_limit_direct
          - action: number.set_value
            metadata: {}
            data:
              value: "-10000"
            target:
              entity_id:
                - number.solax_remotecontrol_push_mode_power_8_9_direct
          - action: select.select_option
            metadata: {}
            data:
              option: Individual Setting – Target SOC Mode
            target:
              entity_id:
                - select.solax_modbus_power_control_direct
                - select.solax_remote_control_power_control_mode_direct
```

also take a look at the discussions under the PR: https://github.com/wills106/homeassistant-solax-modbus/pull/1373
