### ISSUE TITLE
Gen 2 (SK-SU3000E) showing Battery Voltage x 10

### ISSUE THREAD

**Issue by blb4github** [wills106/homeassistant-solax-modbus#73]
The SolaX Battery Voltage Charge entity is showing the battery voltage multiplied by 10, currently it shows 529,8 V.

**Comment by wills106** [comment]
This Integration has only been tested on Pylontech batteries I believe on the Gen2. I am guessing the LG Battery responds different, so I will need a different scale for it.

**Comment by matthewjporter** [comment]
My Second Inverter has LG Chem ESS batteries and works the same as my Pylontech Batteries – Both on SK-SU5000E inverters

From: wills106 ***@***.***>
Reply to: wills106/homsassistant-solax-modbus ***@***.***>
Date: Monday, 23 May 2022 at 17:41
To: wills106/homsassistant-solax-modbus ***@***.***>
Cc: Subscribed ***@***.***>
Subject: Re: [wills106/homsassistant-solax-modbus] Gen 2 (SK-SU3000E) showing Battery Voltage x 10 (Issue #73)


This Integration has only been tested on Pylontech batteries I believe on the Gen2. I am guessing the LG Battery responds different, so I will need a different scale for it.

**Comment by blb4github** [comment]
It's also the Battery Current values which are x10. Power Values are looking fine, see attachement.

<img width="319" alt="Schermafbeelding 2022-05-23 om 21 21 24" src="https://user-images.githubusercontent.com/35904565/169891352-90abada3-4e0c-4cdf-8feb-71ab01d662ac.png">

**Comment by blb4github** [comment]
Thanks, very much appreciated!!

**Comment by wills106** [comment]
What is the battery charge / discharge max current? Is it 50A like on the 5kW version?

**Comment by wills106** [comment]
I have just added in the serial numbers for 3kW & 3.7kW in 0.5.6

After updating to 0.5.6 I would recommend you remove the Integration from the Integration page and readd it, so it detects your Inverter correctly.
Can you let me know if the total entities changes from 55?

**Comment by blb4github** [comment]
I'm not sure which version I'm running, I have deleted the integration and added it again. In the error log I see:

2022-05-24 16:43:44 ERROR (MainThread) [custom_components.solax_modbus] unrecognized inverter type - serial number : U30EDxxxxxxxxxx (My serial number mentioned fully)
2022-05-24 16:44:04 ERROR (MainThread) [custom_components.solax_modbus] must be either HYBRID or AC

**Comment by wills106** [comment]
Did you install through HACS?

You are now on a version of 0.5.x prior to 0.5.6

The first time round when you installed it and went to configure the Integration was there multiple tick boxes to select from?

**Comment by blb4github** [comment]
I did indeed install trough HACS. In the mean time I have seen an upgrade to 0.5.6 is available and I have installed it. Now I have 92 entities available and Current and Battery Voltage is correct now!
<img width="279" alt="Schermafbeelding 2022-05-24 om 20 56 39" src="https://user-images.githubusercontent.com/35904565/170111706-dff3759d-cf1d-42b3-83e9-42ff8b4e23c3.png">

They look like:
<img width="528" alt="Schermafbeelding 2022-05-24 om 21 02 13" src="https://user-images.githubusercontent.com/35904565/170113084-f673c085-8f2b-41f0-bf8d-35f1145cdd05.png">
<img width="254" alt="Schermafbeelding 2022-05-24 om 21 02 39" src="https://user-images.githubusercontent.com/35904565/170113086-b37dac96-9793-448b-b28a-3de0fbb2dddb.png">
<img width="250" alt="Schermafbeelding 2022-05-24 om 21 02 56" src="https://user-images.githubusercontent.com/35904565/170113092-0c417197-ed35-449e-8785-cc41f633a300.png">

**Comment by wills106** [comment]
I think when you first installed it and only got 55 entities this was because you had installed 0.3.x or 0.4.x

When installing on 0.5.x the correct behaviour for an unknown Inverter is the error you experienced just.

> 2022-05-24 16:43:44 ERROR (MainThread) [custom_components.solax_modbus] unrecognized inverter type - serial number : U30EDxxxxxxxxxx

Your Inverter only got added into 0.5.6

**Comment by blb4github** [comment]
Thanks for this work! What do I have to do the be able to change setting via this integration? I don't have the idea something changes if I press one of the buttons.

**Comment by wills106** [comment]
Have you added in the various number and selects to a Dashboard card?


```
entities:
  - entity: select.solax_charger_use_mode
  - entity: select.solax_allow_grid_charge
  - entity: number.solax_battery_charge_max_current
  - entity: number.solax_battery_discharge_max_current
  - entity: number.solax_battery_minimum_capacity
  - entity: number.solax_battery_minimum_capacity_grid_tied
  - entity: number.solax_forcetime_period_1_max_capacity
  - entity: number.solax_forcetime_period_2_max_capacity
  - entity: select.solax_charger_start_time_1
  - entity: select.solax_charger_end_time_1
  - entity: select.solax_charger_start_time_2
  - entity: select.solax_charger_end_time_2
  - entity: button.solax_battery_awaken
  - entity: button.solax_unlock_inverter
  - entity: button.solax_unlock_inverter_advanced
show_header_toggle: false
title: SolaX Battery
type: entities
```

You normally only have to press the unlock_inverter once if you haven't previously connected to the cloud of following a power cycle on the Inverter.
If you enable the disabled by default sensor lock_state what does that return?
