### ISSUE TITLE
Export Control is 10x higher than configured.

### ISSUE THREAD

**Issue by Maergsche** [wills106/homeassistant-solax-modbus#922]
### Describe the bug

Hello, I have a Solax Gen3 Hybrid. The Sliders of the Export Control shows 1448w after I configured the parameter over the Solax App to 14480. 

The Value is 1/10 . 
In the Solax App Values can be set in 20w steps.

### Integration Version

2024.05.7

### Homeassistant core version

2024.6.1

### Inverter brand

Solax X3 Hybrid 8.0-D-E

### Plugin used

plugin_solax.py

### Serial prefix

H3UE08

### Inverter firmware versions

DSP v3.63 ARM v3.53

### Connection Method

Default inten

### Dongle firmware

None

**Comment by Codiwr** [comment]
Another thread with this issue was closed 2 weeks ago on the assumption it had been solved - but it's still an issue.

**Comment by wills106** [comment]
This is implemented in [2024.07.0b1](https://github.com/wills106/homeassistant-solax-modbus/releases/tag/2024.07.0b1)

**Comment by Xeudoron** [comment]
Hi,

I'd like to report same behavior on inverters:

X3-Hybrid-10.0
Firmware: DSP v1.35 ARM v1.34
Hardware: Gen4
SN prefix: H34A10

X3-Hybrid-15.0
Firmware: DSP v1.42 ARM v1.41
Hardware: Gen4
SN prefix: H34A15

Integration version: 2024.05.7
HA Core version: 2024.6.4

When `export control` is set through solaxcloud to any value, then the HA modbus integration shows 10x that value for number.solax_export_control_user_limit
![image](https://github.com/user-attachments/assets/2be2ddaf-1082-496c-9783-48c6ac755573)

same on the other inverter
![image](https://github.com/user-attachments/assets/2a57982b-b228-432d-8bb0-04766bf03663)

**Comment by KOPRajs** [comment]
I'm having the same issue (export control is scaled by 0.1) with the current 2024.08.8 version.

HA: 2024.8.0
SolaX: 2024.08.8
Model: X3-Ultra
Firmware: DSP 80 ARM 14.8
Hardware: Gen5
Serial number: H3BC30JC18xxxx

**Comment by Codiwr** [comment]
This has continued to be incorrect and is still the case on 2024.09.4. Anyone else still finding this?

**Comment by Xeudoron** [comment]
At least for my setup, I found that I can simply set `number.solax_config_export_control_limit_readscale` to 10. So, I created a YAML file that, when needed, sets the required hard-configured values inside the inverter. **Beware of frequent writes to the inverter's Modbus memory**.

```
##=========================================================================##
## COUNTER

counter:
  custom_solax_modbus_counter:
    name: "Inverter Flash Memory Write Counter"
    step: 1
    maximum: 30
    restore: true
    icon: mdi:lifebuoy


##=========================================================================##
## TEMPLATE

template:
  ## Sensor to check if it's possible to write to inverter flash memory (condition for automation)
  - binary_sensor:
      - name: custom_solax_modbus_writes
        state: >
          {% set flash_writes_daily_limit = 20 %}
          {% set flash_writes_counter = states('counter.custom_solax_modbus_counter') | int(default=flash_writes_daily_limit) %}

          {{ flash_writes_counter < flash_writes_daily_limit }}
        availability: >
          {% from 'tools.jinja' import is_valid %}
          {{ 
            is_valid('counter.custom_solax_modbus_counter') | bool
          }}


##=========================================================================##
## AUTOMATION

automation:
  - id: custom_solax_check_config_export_control_limit_readscale
    alias: "Check and Set Export Control Limit Readscale"
    trigger:
      - platform: state
        entity_id: number.solax_config_export_control_limit_readscale
    condition:
      - condition: template
        value_template: "{{ states('number.solax_config_export_control_limit_readscale') in ['unavailable', 'unknown', 'none', None, ''] }}"
      - condition: template
        value_template: "{{ states('number.solax_config_export_control_limit_readscale') != 10 }}"
    action:
      - service: script.custom_solax_set_solax_config_export_control_limit_readscale

  - id: custom_solax_check_config_max_export
    alias: "Check and Set Max Export"
    trigger:
      - platform: state
        entity_id: number.solax_config_max_export
    condition:
      - condition: template
        value_template: "{{ states('number.solax_config_max_export') in ['unavailable', 'unknown', 'none', None, ''] }}"
      - condition: template
        value_template: "{{ states('number.solax_config_max_export') != 30000 }}"
    action:
      - service: script.custom_solax_set_solax_config_max_export

  - id: custom_solax_check_device_lock
    alias: "Check and Set Device Unlock State"
    trigger:
      - platform: state
        entity_id: select.solax_device_lock
    condition:
      - condition: template
        value_template: "{{ states('select.solax_device_lock') in ['unavailable', 'unknown', 'none', None, ''] }}"
      - condition: template
        value_template: "{{ states('select.solax_device_lock') != 'Unlock' }}"
    action:
      - service: script.custom_solax_set_solax_device_lock

  - id: custom_solax_check_lock_state
    alias: "Check and Set Lock State to Unlocked - Advanced"
    trigger:
      - platform: state
        entity_id: select.solax_lock_state
    condition:
      - condition: template
        value_template: "{{ states('select.solax_lock_state') in ['unavailable', 'unknown', 'none', None, ''] }}"
      - condition: template
        value_template: "{{ states('select.solax_lock_state') != 'Unlocked - Advanced' }}"
    action:
      - service: script.custom_solax_set_solax_lock_state

  - id: solax_modbus_counter_reset
    alias: "Reset SolaX Modbus Counter"
    description: "Reset the counter for SolaX Modbus writes daily."
    trigger:
      - platform: time
        at: "00:00:00"
    condition: []
    action:
      - service: script.custom_solax_modbus_counter_reset


##=========================================================================##
## SCRIPT

script:
  custom_solax_modbus_counter_reset:
    alias: "Reset Solax Modbus Counter"
    sequence:
      - service: counter.reset
        target:
          entity_id: counter.custom_solax_modbus_counter
    mode: single

  custom_solax_modbus_counter_increment:
    alias: "Increment Solax Modbus Counter"
    sequence:
      - service: counter.increment
        target:
          entity_id: counter.custom_solax_modbus_counter
    mode: single

  custom_solax_set_all_modbus:
    alias: "Set All SolaX Inverter Modbus Variables"
    sequence:
      - service: script.custom_solax_set_solax_config_export_control_limit_readscale
      - service: script.custom_solax_set_solax_config_max_export
      - service: script.custom_solax_set_solax_device_lock
      - service: script.custom_solax_set_solax_lock_state
    mode: single

  ## Current inverters likely have a bug, and this should help correctly read and set the export limit from the distribution
  custom_solax_set_solax_config_export_control_limit_readscale:
    alias: "Set config_export_control_limit_readscale"
    sequence:
      - condition: template
        value_template: "{{ states('number.solax_config_export_control_limit_readscale') | float != 10 }}"
      - service: number.set_value
        target:
          entity_id: number.solax_config_export_control_limit_readscale
        data:
          value: 10
      - condition: state
        entity_id: binary_sensor.custom_solax_modbus_writes
        state: "on"
      - service: script.custom_solax_modbus_counter_increment
    mode: single

  ## Set max export value, which is linked to other entities such as Active Power, etc.
  ## This might be important for limiting sales due to distribution limits
  custom_solax_set_solax_config_max_export:
    alias: "Set config_max_export"
    sequence:
      - condition: template
        value_template: "{{ states('number.solax_config_max_export') | float != 30000 }}"
      - service: number.set_value
        target:
          entity_id: number.solax_config_max_export
        data:
          value: 30000
      - condition: state
        entity_id: binary_sensor.custom_solax_modbus_writes
        state: "on"
      - service: script.custom_solax_modbus_counter_increment
    mode: single

  ## Unlock the inverter
  custom_solax_set_solax_device_lock:
    alias: "Set device_lock"
    sequence:
      - condition: template
        value_template: "{{ states('select.solax_device_lock') != 'Unlock' }}"
      - service: select.select_option
        target:
          entity_id: select.solax_device_lock
        data:
          option: "Unlock"
      - condition: state
        entity_id: binary_sensor.custom_solax_modbus_writes
        state: "on"
      - service: script.custom_solax_modbus_counter_increment
    mode: single

  ## Unlock the inverter
  custom_solax_set_solax_lock_state:
    alias: "Set lock_state"
    sequence:
      - condition: template
        value_template: "{{ states('select.solax_lock_state') != 'Unlocked - Advanced' }}"
      - service: select.select_option
        target:
          entity_id: select.solax_lock_state
        data:
          option: "Unlocked - Advanced"
      - condition: state
        entity_id: binary_sensor.custom_solax_modbus_writes
        state: "on"
      - service: script.custom_solax_modbus_counter_increment
    mode: single

```
